name: Schedule Website Report

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Exact time to run the Website Report workflow"
        required: true
        type: string
        default: "2026-04-07T12:45:00+05:30"

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule Website Report
        uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.TOKEN }}
          workflow: "Website Report"
          date: ${{ github.event.inputs.date }}
          wait-ms: 45000
